openapi: 3.0.0
info:
  title: money-transfer simulation
  description: money-transfer simulation restful api
  version: "1.0"
servers:
- url: https://virtserver.swaggerhub.com/4-Revolut/money-transfer/1.0
  description: SwaggerHub API Auto Mocking
tags:
- name: user
  description: user operations
- name: account
  description: account operations
paths:
  /user:
    post:
      tags:
      - user
      summary: create new user
      operationId: addUser
      responses:
        201:
          description: user created
        400:
          description: invalid input
        409:
          description: user already exists
components:
  schemas:
    user:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        firstname:
          type: string
        lastname:
          type: string
        email:
          type: string
    account:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        balance:
          type: number
  requestBodies:
    user:
      description: new user to add to the system
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/user'
      required: true
