openapi: 3.0.0
info:
  title: money-transfer simulation
  description: money-transfer simulation restful api
  version: "1.0"
servers:
- url: https://virtserver.swaggerhub.com/4-Revolut/money-transfer/1.0
  description: SwaggerHub API Auto Mocking
tags:
- name: user
  description: user operations
- name: account
  description: account operations
- name: transfer
  description: transfer between accounts
paths:
  /user:
    put:
      tags:
      - user
      summary: updates user
      operationId: editUser
      requestBody:
        description: edit existing user
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        200:
          description: user updated
        400:
          description: invalid input
        404:
          description: user not found
    post:
      tags:
      - user
      summary: creates new user
      operationId: addUser
      requestBody:
        description: create new user
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        201:
          description: user created
        400:
          description: invalid input
        409:
          description: user already exists
  /user/{userid}:
    get:
      tags:
      - user
      summary: Get user by user id
      operationId: getUserById
      parameters:
      - name: userid
        in: path
        description: user id that needs to be fetched
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        200:
          description: user found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        404:
          description: user not found
  /transfer:
    post:
      tags:
      - transfer
      summary: moves money
      operationId: transfer
      requestBody:
        description: transfer details
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/transfer'
      responses:
        200:
          description: transfer successful
        400:
          description: invalid input
components:
  schemas:
    user:
      required:
      - email
      - firstname
      - lastname
      type: object
      properties:
        id:
          type: string
        email:
          maxLength: 30
          minLength: 10
          type: string
          format: email
        firstname:
          maxLength: 15
          minLength: 5
          type: string
        lastname:
          maxLength: 15
          minLength: 5
          type: string
        accountArray:
          $ref: '#/components/schemas/accountArray'
    account:
      type: object
      properties:
        id:
          type: string
        name:
          maxLength: 15
          minLength: 5
          type: string
        balance:
          maximum: 1000.0
          minimum: 0
          type: number
    accountArray:
      type: array
      items:
        $ref: '#/components/schemas/account'
    transfer:
      required:
      - amount
      - credit-account-id
      - debit-account-id
      type: object
      properties:
        debit-user-id:
          maxLength: 36
          minLength: 36
          type: string
        debit-account-id:
          maxLength: 36
          minLength: 36
          type: string
        credit-user-id:
          maxLength: 36
          minLength: 36
          type: string
        credit-account-id:
          maxLength: 36
          minLength: 36
          type: string
        amount:
          maximum: 5000.0
          minimum: 0
          type: number
  requestBodies:
    user:
      description: new user to add to the system
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/user'
      required: true
