openapi: 3.0.0
info:
  title: money-transfer simulation
  description: money-transfer simulation restful api
  version: "1.0"
servers:
- url: https://virtserver.swaggerhub.com/4-Revolut/money-transfer/1.0
  description: SwaggerHub API Auto Mocking
paths: {}
components: {}
